insert into item (name, description, price, category, type) values ("Ceiling fan", "id volutpat lacus laoreet non", 50, "Electrical", "Fixture");
insert into item (name, description, price, category, type) values ("Ceiling Light", "id volutpat lacus laoreet non", 75, "Electrical", "Fixture");
insert into item (name, description, price, category, type) values ("Dishwasher", "id volutpat lacus laoreet non", 550, "Plumbing", "Appliance");
insert into item (name, description, price, category, type) values ("Refrigerator", "id volutpat lacus laoreet non", 1200, "Electrical", "Appliance");
insert into item (name, description, price, category, type) values ("Toilet", "id volutpat lacus laoreet non", 250, "Plumbing", "Fixture");
insert into item (name, description, price, category, type) values ("Electric Fireplace", "id volutpat lacus laoreet non", 150, "Electrical", "Fixture");
insert into item (name, description, price, category, type) values ("Shower", "id volutpat lacus laoreet non", 1200, "Plumbing", "Fixture");
insert into item (name, description, price, category, type) values ("Hardwood", "id volutpat lacus laoreet non", 100, "Finishes", "Flooring");
insert into item (name, description, price, category, type) values ("Paint", "id volutpat lacus laoreet non", 50, "Finishes", "Walls");
insert into item (name, description, price, category, type) values ("Baseboards", "id volutpat lacus laoreet non", 200, "Finishes", "Trim");